name: Newman Run

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: newman-tests.postman_collection.json
          reporters: '["html"]'
          envVar: '[{ "key": "baseUrl", "value": "https://fakerapi.it/api/v1/" }]'
