name: Newman Tests

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  run_newman_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@master
      with:
        collection: postman_collection.json
        reporters: '["emojitrain"]'
        delayRequest: 5000
        envVar: '[{ "key": "baseUrl", "value": "https://fakerapi.it/api/v1/" }]'
